### PR TITLE
Fixed In-Game Config menu not showing

### PR DESCRIPTION
**Pull request by NovaViper**
Changed some info in mcmod.info

### CODE REVIEW

**Comment by 61352151511** [comment]
I've manually applied the changes in the newer update and the config button is still not functional. I'm going to push the changes for 4.1.1 and if you could pull it and test it out, see if you can find out why it's not working, that would be great. The only real change in this pull request was the casing of the modid in the mcmod.info file, which does not fix the issue.

**Comment by NovaViper** [comment]
I did go test it out but it started working for me.. strange ._.

**Comment by 61352151511** [comment]
That is strange, download the 1.11.2 branch and build the mod. Let me know if it's working in game, it's not in development environment

**Comment by NovaViper** [comment]
Ah, ha! I found our solution! It seems that things have changed with 1.11.2 in the configurations. I've looked at [what Just Enough Items has done](https://github.com/mezz/JustEnoughItems/blob/1.11/src/main/java/mezz/jei/config/JEIModGuiFactory.java) and it all works now. I'm having problems pushing the results though.. as my fork won't update to your branch's current commit

**Comment by NovaViper** [comment]
Added commit bc4c3d9

**Comment by 61352151511** [comment]
Thanks, I've fixed this using the code you provided and pushed it into the repo. Only two changes needed to be made so rather than merge this PR I just made those two line changes and pushed that. Thanks for the help!

**Comment by NovaViper** [comment]
Np! I'll be happy to help with any more problems!

**Pull request closed without merging**
